# Generated by Django 3.2.8 on 2021-10-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
